version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
    depends_on:
      - api
      - ui
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - mynetwork
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - mynetwork
  redis:
    image: redis:latest
    networks:
      - mynetwork

networks:
  mynetwork:
